import type { Metadata } from "next";
import { Kode_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";

const kodeMono = Kode_Mono({
  subsets: ["latin"],
  weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: "My Portfolio | hiaayush30",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kodeMono.className} antialiased text-white`}
      >
        <div className="absolute w-full -z-10 items-center px-5 py-2 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">
          {children}
          <CustomCursor />
        </div>
      </body>
    </html >
  );
}
